### ISSUE TITLE
<br> broken?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#11]
![2018-03-01 10_31_38-defold editor 2 0 - vn](https://user-images.githubusercontent.com/409170/36862492-d092212a-1d3b-11e8-9eff-c88de0df471f.png)
![2018-03-01 10_31_43-vn](https://user-images.githubusercontent.com/409170/36862501-d3efa536-1d3b-11e8-9e66-12255a635002.png)

![2018-03-01 10_31_53-defold editor 2 0 - vn](https://user-images.githubusercontent.com/409170/36862503-d6678022-1d3b-11e8-9712-b0fffb1ce927.png)
![2018-03-01 10_32_00-vn](https://user-images.githubusercontent.com/409170/36862505-d89d7270-1d3b-11e8-83a4-61623b68c271.png)

**Comment by subsoap** [comment]
<br/> works <br> does not

**Comment by britzl** [comment]
Yes, `<br>` is not supported. It should be `<br/>`.

(`<br></br>` should also work)

**Comment by subsoap** [comment]
I'll close, may want to include that in the readme.

**Comment by britzl** [comment]
Not sure it would be worth the effort to add support for <br> without a closing tag even though it's accepted by most (all?) browsers. I don't want to complicate the parser more than necessary.

**Comment by subsoap** [comment]
Just include in the readme that if using <br> then <br></br> is required.

**Comment by britzl** [comment]
Yeah, update the readme (section on linebreaks)
