### ISSUE TITLE
Get last char x,y position

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#12]
Would be useful when doing per character effects

**Comment by britzl** [comment]
What is it that you need specifically? I didn't really understand. If have a word "object" you have access to the node (so that you can get position) and the text metrics.

**Comment by subsoap** [comment]
It could as a helper to get the position used to spawn individual character glyphs as an effect at the tail end of a body of text. It's sometimes an effect used in visual novels as individual characters are added to bodies of dialog text. I'll make an example, maybe it can be a part of vn kit.

**Comment by britzl** [comment]
Ok, you mean so that the text is displayed one character at a time until entire text is revealed?

Could that be done via the truncate() function (https://github.com/britzl/defold-richtext/issues/14)?

**Comment by subsoap** [comment]
Yes, but consider the polish effect of having single characters "slam" down as the body of text is truncated less and less, so need positioning of that in same way. It's a rare effect that not many people will want to use but some might. I can probably put it into vn instead.

**Comment by britzl** [comment]
Ah, ok, now I understand. Yeah, that would be a pretty cool effect! I think maybe it's better to implement outside of defold-richtext though. I believe all the data that you need is available to you.

**Comment by britzl** [comment]
This should be handled by richtext.truncate() and richtext.characters() right? Although it would mean that a lot of extra nodes are created. Hmm, maybe better to do a custom solution specifically for this?
