### ISSUE TITLE
Truncate to x many chars while ignoring tags

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#14]
So ```<size=1>Lara</size><br/><size=0.7>Well, hello there!</size>``` could be truncated to

```<size=1>Lara</size><br/><size=0.7>Well, h</size>``` for whatever function helper name could be.

This is so RPG style per char text showing can be easily done.

**Comment by britzl** [comment]
I wonder if it wouldn't be acceptable to first do:

local words, metrics = richtext.create("full text", font, settings)
richtext.truncate(words, length)

The truncate() function would disable nodes that shouldn't be shown at all and change the text on the node that needs to be truncated.

**Comment by britzl** [comment]
Added richtext.truncate(words, length).

https://github.com/britzl/defold-richtext/releases/tag/2.4.0
