### ISSUE TITLE
richtext.update(nodes, text, font, settings) ?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#15]
An easy way of rebuilding richtext bodies as elements within are changed?

**Comment by britzl** [comment]
What kind of changes are we talking about? Changing of word in the text?

How would the update() function actually work?

**Comment by subsoap** [comment]
Check through existing nodes and update / replace them without needing to rebuild all nodes?

Changes would be for example adding one character at a time to a text body.
