### ISSUE TITLE
Helper function to get number of characters including spaces while ignoring tags

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#16]

**Comment by britzl** [comment]
Ah, good one. Perhaps it could be returned with the metrics from a call to richtext.create()?

**Comment by subsoap** [comment]
It would be useful to return it, but as a stand alone function as well. It would be used for example to dynamically decide where to put linebreak when creating bodies of text line by line so that a "word" does not suddenly jump lines when it overflows the width.

**Comment by britzl** [comment]
Added `richtext.length()` which can take either a string with text (incl tags) or a list of words (from `richtext.create`).

Length is also included as `char_count` in the metrics returned from `richtext.create()`

https://github.com/britzl/defold-richtext/releases/tag/2.4.0
