### ISSUE TITLE
Sprites being scaled when they shouldn't be?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#21]
What's happening here? There are two icons. One is displayed like how it should be, the second looks incorrect. I tried to reset the size but it did not seem to help.

```
local text = [[<img=icons:document/><size=1>Kalipi</size><br/><size=0.7>Well, hello there! He he he... ho ho ho...</size><br/><size=0.7>What do we have here?</size><size=1.0></size><img=icons:document/>]]		
```

![2018-03-06 22_48_37-vn](https://user-images.githubusercontent.com/409170/37077637-a2a3821e-2190-11e8-8088-71846f2e27ae.png)

Adding some size 1 text doesn't help either

![2018-03-06 22_51_31-vn](https://user-images.githubusercontent.com/409170/37077702-f66d0078-2190-11e8-8326-9d0ca776d336.png)

Putting second on its own line also doesn't help

![2018-03-06 22_52_36-vn](https://user-images.githubusercontent.com/409170/37077740-1da39c42-2191-11e8-8cbb-ab9bdec717ec.png)

**Comment by subsoap** [comment]
It's because the node position is like this DEBUG:SCRIPT: vmath.vector3(0, -102.59999847412, 0)
I tested forcing the node to vmath.vector3(0, -102, 0)

![2018-03-06 22_57_01-vn](https://user-images.githubusercontent.com/409170/37077868-b33f5f52-2191-11e8-9dc4-605f323025bb.png)

So may need a feature to floor/round the position of sprites so they align with the pixel grid.

**Comment by britzl** [comment]
Ah, I see. Should that be an option perhaps? And what should the option be called?

**Comment by subsoap** [comment]
Something like image_pixel_grid_snap = true

**Comment by britzl** [comment]
Added the setting and released a new version: https://github.com/britzl/defold-richtext/releases/tag/3.0.0
