### ISSUE TITLE
How to reuse already created nodes?

### ISSUE THREAD

**Issue by Ogimle** [britzl/defold-richtext#27]
for expample 
```
rnode = richtext.create('<color=red>my text</color>')
.... somewhere deep in code ....
rnode.text += '<color=green>new text</color>'
```

**Comment by britzl** [comment]
defold-richtext doesn't support node reuse. If you need to make a change to RichText created nodes you're currently forced to either do the changes yourself manually or call richtext.create() again (don't forget to delete the old nodes).

**Comment by Ogimle** [comment]
richtext.create() dont return links to created nodes
how to get "old" nodes?

**Comment by Ogimle** [comment]
ok, i see
thanks

**Comment by britzl** [comment]
There could perhaps be an option to append more text to already created text, but in the case of inserting text it would be to messy code-wise to solve the whole reflow and repositioning of text node. How often do you need to append more text to already created RichText?

**Comment by Ogimle** [comment]
not often, but I'm planning a scrolled log
I studied the plugin, I will modify and introduce the concept of strings, methods to add, delete, move

**Comment by britzl** [comment]
Won't fix.
