### ISSUE TITLE
richtext.truncate for truncating one word at a time

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#38]
Would be a useful option

**Comment by britzl** [comment]
Hmm, good suggestion. Maybe add an option table as a third argument with an option to truncate full words/to word boundary:

    richtext.truncate(words, length, { full_word = true }) -- option name?

**Comment by subsoap** [comment]
yes, settings table would work for this

**Comment by britzl** [comment]
@subsoap I need to discuss the design a bit more:

* If we add an option to truncate to full words, then if the result of a call to truncate() would result in 
 a partial word, the function should remove that entire word right? Truncating "up" to include a full partial word is probably never something you'd like to do right?

```
         11111111112
12345678901234567890
Hi my name is Slim Shady

truncate(words, 16)

         11111111112
12345678901234567890
Hi my name is Sl

truncate(words, 16, { full_word = true })

         11111111112
12345678901234567890
Hi my name is
```

**Comment by britzl** [comment]
PR https://github.com/britzl/defold-richtext/pull/46

**Comment by subsoap** [comment]
Yes, you should "round down" the words"

Although when truncating full words the counter should probably be for the actual word count and not the character accounts, single words would be a single number in the total truncation value

**Comment by britzl** [comment]
Good point. This has been implemented and released in 5.9.0

**Comment by subsoap** [comment]
Multiple &zwsp; with no spaces between are considered a single word. Probably want them each to be considered their own word because otherwise defeats their purpose.

**Comment by britzl** [comment]
Good point. This is required when truncating per word.

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/defold-richtext/releases/tag/5.10.2
