### ISSUE TITLE
Adding extra waiting time for create_truncate_example()

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#39]
It would be useful if it were somehow possible to add tags like <wait=1/> to be able to skip timer.delay repeats based on those kinds of tags. Maybe being able to check the next word/tag see if it's a wait tag and live edit it so it's at or below 0?

This would be useful to add a little time between line breaks / add suspense in text.

**Comment by britzl** [comment]
You could add zero-width space characters to your text to add a delay:

    \226\128\139

**Comment by subsoap** [comment]
Good idea!

**Comment by subsoap** [comment]
Although it ends up looking like this

![1](https://user-images.githubusercontent.com/409170/64116616-abc99e00-cd47-11e9-8031-6af29dd79175.png)

![2](https://user-images.githubusercontent.com/409170/64116615-abc99e00-cd47-11e9-9cc2-0eccab32b6af.png)

**Comment by subsoap** [comment]
Maybe runtime solution would be to swap a special tag with the marked number of zero-width chars.

**Comment by britzl** [comment]
Maybe add a new tag `<zwsp repeat=5/>` to insert `repeat` number of zero-width space characters?

Or maybe add a generic custom tag handler where you could register a handler for a tag and when it is encountered you get any enclosed text as an argument your tag handler function.

I'll think a bit on this and see what can be done. This week is a bit crazy but on Friday we have an exploration day in the team. I'll do some work on Defold-RichText then.

**Comment by subsoap** [comment]
<zwsp repeat=5/> would be good enough for my use case.

**Comment by subsoap** [comment]
Was <zwsp repeat=5/> added or &zwsp; by itself?

**Comment by britzl** [comment]
Only &zwsp; for now

**Comment by subsoap** [comment]
For future searching reference, if something is zwsp it gets a zwsp tag. So you can skip zwsp characters for effects.

```if last_word.tags and not last_word.tags.zwsp then```

**Comment by britzl** [comment]
Yes, good point. Each &zwsp; will be converted into a <zwsp> tag with inner content set to \226\128\139. This allows for searching of the tags etc

**Comment by subsoap** [comment]
![text_particles](https://user-images.githubusercontent.com/409170/64673142-33876a80-d422-11e9-95e8-5c8eaf7197f4.gif)
