### ISSUE TITLE
Add support for displaying images in the text

### ISSUE THREAD

**Issue by britzl** [britzl/defold-richtext#4]
Box nodes. Perhaps using `<img>` tag?

**Comment by subsoap** [comment]
How would it work?
```
<img src="texture_name"></img>
<img>texture_name</img>
```

**Comment by britzl** [comment]
Or maybe `<img="texture_name"></img>` or `<img=texture_name></img>`

The system is not setup to parse `<img>texture_name</img>`. Parameters should be inside the tag, like in `<size=2>` and `<color=red>`

And maybe I need to add support for <foobar/> to immediately close a tag. It should be easy to parse.

**Comment by subsoap** [comment]
```<img="texture_name"/>```

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/defold-richtext/releases/tag/2.1.0
