### ISSUE TITLE
How to deal with exceeding the node limit?

### ISSUE THREAD

**Issue by rgrams** [britzl/defold-richtext#47]
I don't think that RichText should to handle this case explicitly, I'm just wondering if you have any ideas how to solve this for my project. 

I'm dealing with quite a bit of text, generally filling the screen. I'm using the combine_words option, and most of the time, most of the text is plain, so there is no issue at all. But sometimes I will have text that definitely exceeds the 1024 max node limit per gui. I'm making a MUD client (an interface for online text-adventure games), so I'm not in control of the text that I get, only what I do with it. I know I need to split things between multiple GUI components, I'm just not sure what the best way to split it up is.

Some ways I've thought about:

1. Always split my text into a preset number of large chunks (3-5?).
    * Simple, but not guaranteed to succeed (i.e would crash) in extreme cases. 
2. Always split the text into 1024-character pieces.
    * Still simple, should always work, but seems very inefficient for not being needed 90% of the time.
2. Count tags and split it up dynamically?
    * Should maybe always work, but not so simple. 
    * I don't think I could get an accurate node count without fully parsing the text an extra time, which seems dumb.
3. Fork & modify RichText to split the "pipeline" into multiple function calls.
    * Should always work, sounds "clean", but requires probably non-trivial changes to RichText.
    * Something like:
        1. Parse.
        2. Combine words. (+ calculate line breaks, etc.?)
        3. Divide word list if there are more than 1024 nodes.
        4. Create nodes in however many GUIs are needed.

**Comment by britzl** [comment]
I really don't like any solution other than 4. I've thought of doing 4 before, but as you say, it's non-trivial to do the change. An advantage of separating the parse step from the node creation is that the result from parsing the text could be cached and even stored on disk if needed.

**Comment by britzl** [comment]
We have increased max node count to 8192 in gui scenes. This is hopefully not as much of a problem anymore. Closing.
