### ISSUE TITLE
Ability to use all directional alignment basic gui objects have

### ISSUE THREAD

**Issue by Qwarr** [britzl/defold-richtext#50]
Currently you can only do left, center and right. Would it be possible to add in the others such as gui.PIVOT_SE, gui.PIVOT_NW, etc

**Comment by britzl** [comment]
The align property defines how the words on each line should be positioned in relation to the position provided when calling richtext.create().

The algorithm iterates word for word from the start of the text until a line is full and at that point it positions the words of the line according to the align property. This means that it always has to vertically align from the top, ie the first line starts at the provided vertical position, the next line below that and so on. It would be quite a bit more complex to vertically align the text some other way.

My recommendation is that you provide a parent node when you call richtext.create() and then reposition the node vertically.
