### ISSUE TITLE
wait tag

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#56]
I added this tag to a custom version of RichText for my needs in a visual novel style project. It would probably be useful for others but I'm not sure if it should be a part of the main project. These are the main changes.

```
	elseif tag == "wait" then
		settings.wait = tonumber(params)
```

```
		if is_empty then
			-- empty tag, ie tag without content
			-- example <br/> and <img=texture:image/>
			local tag_settings = parse_tag(name, params)
			merge_tags(word_settings, tag_settings)
			local add_this_word = ""
			if tag_settings.wait ~= nil and tag_settings.wait > 0 then
				local wait_word = "\226\128\139"
				for i=1, tag_settings.wait do
					add_this_word = add_this_word .. wait_word
				end
			end
			add_word(add_this_word, word_settings, all_words)
		elseif not is_endtag then
```

Then the tag is used like ```<wait=30>``` which inserts 30 zero width characters. This is useful in visual novel projects where you have text appearing once character at a time and you want to add small delays between actions.

**Comment by subsoap** [comment]
If a wait tag is added similar to this then an action tag should be added too <action=sound:ding/> then these actions can be listened to within timer.delay(), and acted upon when using the truncate feature in games like visual novels.

**Comment by britzl** [comment]
The wait tag is interesting but feels a bit too game specific. Maybe a "repeat" tag that will repeat the enclosed text one or more times?

Or maybe it should be possible to specify a callback function which will be invoked when an unknown tag is encountered while parsing the text. This would allow developers to handle game specific tags while parsing text.

The "action" tag is also quite interesting. The tag could trigger a callback function which would allow developers to react to these actions/events when encountered.

**Comment by subsoap** [comment]
Callback function methods would be cool as a way to define custom tag behavior / react to action tags. What I am doing in my project is using Broadcast to signal the data that is then used elsewhere. Playing sounds / animations / screen effects as certain text passes by.

```<repeat=time:text/>``` ?

**Comment by subsoap** [comment]
Another example of how I'm using action tag, when this text is truncated a particlefx is positioned on the char and plays to give an effect to make that text more special.

```
"<action=particles:text_emitter>Make this pretty</action>"
```

**Comment by britzl** [comment]
For the repeat tag I was thinking like this:

    <repeat=10>&zwsp;</repeat>

**Comment by subsoap** [comment]
That would work well.
