### ISSUE TITLE
Add size as a create settings field to set the default scale

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#61]
Users will want to be able to set the default size of the characters of a body of text without wrapping it all in a <size> tag, while still having the relative sizing amounts of internal <size> tags of that body of text.

Possibly another name in the create setting would be more appropriate but I think ```size``` would be fine since it's the same as the tag.

**Comment by britzl** [comment]
Thank you for the suggestion. Having a default size makes sense. (I do not have time to look into this at the moment.)
