### ISSUE TITLE
Offset shadowed text / images

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#62]
![2020-08-01 19_01_24-dialog png @ 300% (RGB_8)](https://user-images.githubusercontent.com/409170/89113724-7337b600-d429-11ea-8b23-a81a3a18ba4c.png)

This is an effect I need to create with truncated text, a copy of the text/images below set to black color / the images set to black. I am thinking the easiest way for me to do it would be to create a duplicate of the main functions which ignores all color tags / add a way to ignore color tags, and add a way to set the color of images as currently color tags are not impacting images (which is probably a good thing though a consideration for tinting images within text eventually may be wanted). 

This kind of shadow effect is common in games (especially mobile games) so may be worth making it a field in the normal create functions to support somehow.

**Comment by subsoap** [comment]
I got it to work in my project, in a slightly ugly way but it works. Added as setting to blackout everything no matter their tags, then created 2 truncated texts one with the blackout setting enabled and one without and managed both where the first one was only managed before.

**Comment by britzl** [comment]
I'm not entirely sure I understand the problem. Can't you use a Defold font file with a shadow enabled?

**Comment by britzl** [comment]
No more information provided. Closing.
