### ISSUE TITLE
Long Text

### ISSUE THREAD

**Issue by GreenArrow18** [britzl/defold-richtext#67]
If I specify a width of let's say 200 pixels, and then pass a very long text (no spaces, e.g. website url) that exceeds this width, can richtext break this into multiple lines?

Right now, the long text appears in a single line, exceeding the max width, which is not ideal. I was expecting that the long text would be broken down into multiple lines once the specified max width is exceeded.

Use case: chat messages.

**Comment by britzl** [comment]
RichText does not support this at the moment, but it could definitely be supported through a new option.
