### ISSUE TITLE
ALIGN_JUSTIFY last line bug

### ISSUE THREAD

**Issue by Bethleem** [britzl/defold-richtext#68]
When a richtext is created with ALIGN_JUSTIFY parameter and the last line is´nt a full line, the extra space from the last character to the right border is divided and added as space between the words of the line, even if you end the line with a \<br/> or \</p>. It is "justifying" all that free space that should remain as a whole before the last character of that last line.

![imagen](https://user-images.githubusercontent.com/17690275/108604308-68d10f80-73ad-11eb-9f6c-80b1ae60788c.png)

**Comment by britzl** [comment]
Could you please share the string you used? I'm unable to reproduce it.

**Comment by britzl** [comment]
Thanks for the repro!
