### ISSUE TITLE
Spacing between words/nodes

### ISSUE THREAD

**Issue by MamontRussel** [britzl/defold-richtext#70]
It will be good to have option to change distance between words(nodes). Like right now distance is longer than distance between words in regular text node.

Top - regular text node. Bottom - richtext. Distance between words are visually bigger.
![image](https://user-images.githubusercontent.com/5821628/133005754-18422f70-48de-4c6e-878a-f2c72b9b8eef.png)

**Comment by astrochili** [comment]
Could be related to #66.
