### ISSUE TITLE
Text alignment like pivot in text node

### ISSUE THREAD

**Issue by MamontRussel** [britzl/defold-richtext#71]
It will be good to have option to align text similar to regular text nodes (via pivot setting).

Top - regular text node with pivot set to Center. Bottom - richtext.
![image](https://user-images.githubusercontent.com/5821628/133005951-1d5e1ab5-a79d-4b8b-ad2c-119532588a49.png)

**Comment by britzl** [comment]
@MamontRussel I don't quite understand this request. There is an option to align text horizontally using `richtext.ALIGN_LEFT`, `richtext.ALIGN_CENTER`, `richtext.ALIGN_RIGHT` and `richtext.ALIGN_JUSTIFY`.

**Comment by MamontRussel** [comment]
Yes, I know. But it looks like it does not work correctly in my case. Here is the settings for the text on picture above:

`local setup = {
		width = t.t_size_x,
		parent = gui.get_node("Tutorial Text"),
		align = hash("richtext.ALIGN_CENTER"),
		valign = hash("richtext.VALIGN_MIDDLE"),
		position = vmath.vector3(-metrics.width/2 + 50, -300, 0)
}`

Moreover other align options, does not affect it as well.

**Comment by britzl** [comment]
> align = hash("richtext.ALIGN_CENTER"), valign = hash("richtext.VALIGN_MIDDLE")

You should not hash the values. They are defined as constants on the richtext module. Use them like this:

```
local setup = { width = t.t_size_x, parent = gui.get_node("Tutorial Text"), align = richtext.ALIGN_CENTER, valign = richtext.VALIGN_MIDDLE, position = vmath.vector3(-metrics.width/2 + 50, -300, 0) }
```

**Comment by MamontRussel** [comment]
Yes, that's it. My mistake. Thanks.
