### ISSUE TITLE
Multiple repeat tags causes Lua memory allocation error.

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-richtext#72]
richtext.create with

"test<repeat=40>&zwsp;</repeat><repeat=40>&zwsp;</repeat>"

=

ERROR:SCRIPT: Lua memory allocation error.

**Comment by britzl** [comment]
I assume something like this?

```
richtext.create("test<repeat=40>&zwsp;</repeat><repeat=40>&zwsp;</repeat>", "Roboto", settings)
```
