### ISSUE TITLE
valign doesn't seem to be doing anything

### ISSUE THREAD

**Issue by Qwarr** [britzl/defold-richtext#85]
When trying to do use valign to center the text it only ever acts like VALIGN_TOP. 

```lua
	local text = "Long string of text to test the valign settings option in richtext."
	local settings = {
		fonts = {
			pixel = {
				regular = hash("system_font_df"),
			},
		},
		size = 1,
		width = 400,
		parent = gui.get_node("root"),
		position = vmath.vector3(0, 0, 0),
		align = richtext.ALIGN_CENTER,
		valign = richtext.VALIGN_MIDDLE,
		combine_words = true
	}
	
	self.rt_text = richtext.create(text, "pixel", settings)
```
![2023-05-17 14_44_02-richtext_set_enable](https://github.com/britzl/defold-richtext/assets/2577547/6c0bd9fc-2f01-480e-9d08-3da0f77ab362)

Or am I miss understanding how to use valign?

**Comment by britzl** [comment]
The `valign` option controls how text (and images) of different sizes align within a line. Example:

<img width="429" alt="Screenshot 2023-06-08 at 12 48 43" src="https://github.com/britzl/defold-richtext/assets/1300688/16e14e40-d8f6-4e0b-97cc-b3ea05da7a3f">

**Comment by Qwarr** [comment]
Ah miss understood how it worked then, all good I found a work around for what I needed.
