### ISSUE TITLE
The JUSTIFY alignment does not behave correctly

### ISSUE THREAD

**Issue by Morgerion** [britzl/defold-richtext#90]
The JUSTIFY alignment does not behave correctly:
![image](https://github.com/user-attachments/assets/1900b4b9-3670-4355-ad7a-f3dae27c9dc9)

The important problem is the so-called ‘dangling strings’.
In the current implementation, they are aligned, although according to classical JUSTIFY rules they should not be.

![image](https://github.com/user-attachments/assets/fb5039cc-7a27-4e6c-a45a-7b68a80c9f6e)

The essence of the rule is that a line should be aligned ONLY if it ends by moving the text to the next line.
If a line ends with a carriage return and fits entirely within the width, it should be aligned as LEFT.

**Comment by britzl** [comment]
Thanks. I think I got the rules right?

<img width="284" alt="Screenshot 2024-10-03 at 10 13 43" src="https://github.com/user-attachments/assets/7fd0b8f3-8bc5-455f-8bde-5f23355dd247">

**Comment by Morgerion** [comment]
Thank you so much, this is just what is needed!
